version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: bxt-ddr.centralus.cloudapp.azure.com:5001/dockerdemoorg/spring-petclinic-db
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - spring-petclinic-net
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  web:
    build:
      context: .
    image: bxt-ddr.centralus.cloudapp.azure.com:5001/dockerdemoorg/spring-petclinic
    ports:
      - "80:8080"
    networks:
      - spring-petclinic-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - "db"
networks:
  spring-petclinic-net:
    driver: overlay
