version: '3'
services:
  web:
    build:
      context: .
    image: bxtp4p/spring-petclinic
    ports:
      - "8080:8080"
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: bxtp4p/spring-petclinic-db
    ports:
      - "3306:3306"