version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: bxtp4p/spring-petclinic-db:${POM_VERSION:-latest}
    networks:
      - spring-petclinic-net
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  web:
    build:
      context: .
    image: bxtp4p/spring-petclinic:${POM_VERSION:-latest}
    ports:
      - "80:8080"
    networks:
      - spring-petclinic-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - "db"
networks:
  spring-petclinic-net:
    driver: overlay